services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://goserv:gopass@postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - elo-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=goserv
      - POSTGRES_PASSWORD=gopass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbsetup.sql:/docker-entrypoint-initdb.d/dbsetup.sql
    networks:
      - elo-network

volumes:
  postgres_data:

networks:
  elo-network:
    driver: bridge 