services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://goserv:gopass@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
      - FLY_API_KEY=${FLY_API_KEY}
      - FLY_API_HOSTNAME=${FLY_API_HOSTNAME}
      - FLY_APP_NAME=${FLY_APP_NAME}
      - HCLOUD_TOKEN=${HCLOUD_TOKEN}
    depends_on:
      - postgres
      - redis
    networks:
      - elo-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=goserv
      - POSTGRES_PASSWORD=gopass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbsetup.sql:/docker-entrypoint-initdb.d/dbsetup.sql
    networks:
      - elo-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - elo-network

volumes:
  postgres_data:
  redis_data:

networks:
  elo-network:
    driver: bridge 