# fly.toml app configuration file generated for elo-service on 2025-06-07T00:25:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elo-service'
primary_region = 'sea'

[processes]
  app = "./main"

[env]
  FLY_APP_NAME = "elo-service"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  processes = ['app']

