# fly.toml app configuration file generated for elo-service on 2025-06-07T00:25:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elo-service'
primary_region = 'sea'

[processes]
  app = "./main"
  proxy = "./game-server-proxy"

[env]
  FLY_APP_NAME = "elo-service"

# Main app HTTP service
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Proxy HTTP service
[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["proxy"]
  force_https = true

  [[services.ports]]
    port = 8081
    handlers = ["http"]

  [[services.ports]]
    port = 8443
    handlers = ["tls", "http"]

# Proxy TCP service
[[services]]
  protocol = "tcp"
  internal_port = 8081
  processes = ["proxy"]

  [[services.ports]]
    port = 8082

# Main app VM
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  processes = ['app']

# Proxy VM
[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
  processes = ['proxy']
  networks = ['game-servers']
