name: CI / Deploy

on:
  push:
    branches:
      - main
      - production # TODO: Separate deployment
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - name: Build
      run: go build ./...
    - name: Run integration tests
      run: go test -count=1 -timeout 180s ./tests/integration/...

  deploy:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Fly.io CLI
      uses: superfly/flyctl-actions/setup-flyctl@v1
    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
